export const productList = [
  {
    url: '/card-image.png',
    rating: 5,
    ratingCount: 999,
    location: 'Vịnh Lan Hạ',
    title: 'Du Thuyền Stellar of the Seas',
    desciption: 'Hạ thuỷ 2018 - Tàu vỏ kim loại - 22 phòng',
    price: 3350000,
    originalPrice: 5400000,
    tags: ['Du thuyền nổi bật', 'Ưu đãi hè 2022', 'Bể bơi ngoài trời', 'Xe đưa đón'],
  },
  {
    url: '/card-image.png',
    rating: 5,
    ratingCount: 999,
    location: 'Vịnh Lan Hạ',
    title: 'Du Thuyền Stellar of the Seas',
    desciption: 'Hạ thuỷ 2018 - Tàu vỏ kim loại - 22 phòng',
    price: 3350000,
    originalPrice: 5400000,
    tags: ['Du thuyền nổi bật', 'Ưu đãi hè 2022', 'Bể bơi ngoài trời', 'Xe đưa đón'],
  },
  {
    url: '/card-image.png',
    rating: 5,
    ratingCount: 999,
    location: 'Vịnh Lan Hạ',
    title: 'Du Thuyền Stellar of the Seas',
    desciption: 'Hạ thuỷ 2018 - Tàu vỏ kim loại - 22 phòng',
    price: 3350000,
    originalPrice: 5400000,
    tags: ['Du thuyền nổi bật', 'Ưu đãi hè 2022', 'Bể bơi ngoài trời', 'Xe đưa đón'],
  },
  {
    url: '/card-image.png',
    rating: 5,
    ratingCount: 999,
    location: 'Vịnh Lan Hạ',
    title: 'Du Thuyền Stellar of the Seas',
    desciption: 'Hạ thuỷ 2018 - Tàu vỏ kim loại - 22 phòng',
    price: 3350000,
    originalPrice: 5400000,
    tags: ['Du thuyền nổi bật', 'Ưu đãi hè 2022', 'Bể bơi ngoài trời', 'Xe đưa đón'],
  },
  {
    url: '/card-image.png',
    rating: 5,
    ratingCount: 999,
    location: 'Vịnh Lan Hạ',
    title: 'Du Thuyền Stellar of the Seas',
    desciption: 'Hạ thuỷ 2018 - Tàu vỏ kim loại - 22 phòng',
    price: 3350000,
    originalPrice: 5400000,
    tags: ['Du thuyền nổi bật', 'Ưu đãi hè 2022', 'Bể bơi ngoài trời', 'Xe đưa đón'],
  },
  {
    url: '/card-image.png',
    rating: 5,
    ratingCount: 999,
    location: 'Vịnh Lan Hạ',
    title: 'Du Thuyền Stellar of the Seas',
    desciption: 'Hạ thuỷ 2018 - Tàu vỏ kim loại - 22 phòng',
    price: 3350000,
    originalPrice: 5400000,
    tags: ['Du thuyền nổi bật', 'Ưu đãi hè 2022', 'Bể bơi ngoài trời', 'Xe đưa đón'],
  },
]
